Parameters:
# Common
  YYYYMMDD:
    Description: Input a today's date. Do not change as much as possible.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /serverless-framework-handson/YYYYMMDD
    AllowedValues: 
      - /serverless-framework-handson/YYYYMMDD
  HandsonName:
    Description: Input a handson name. Do not change as much as possible.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /serverless-framework-handson/HandsonName
    AllowedValues: 
      - /serverless-framework-handson/HandsonName

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Common
        Parameters: 
          - YYYYMMDD
          - HandsonName

Resources:
  ServerlessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${YYYYMMDD}-${HandsonName}-iam-role
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${YYYYMMDD}-${HandsonName}-iam-policy
          PolicyDocument:
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": "*",
                  "Resource": "*"
                }
              ]
            }

  SSMServerlessRole:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${HandsonName}/ServerlessRoleName
      Value: !Ref ServerlessRole
      Type: String

