# Yml file that builds the following AWS resources
# |Resource|Number|
# |---|---|
# |SSM Parameter|2|


Parameters:
# Common
  YYYYMMDD:
    Description: Input a today's date. ex)20200704
    Type: String
  HandsonName:
    Description: Input a handson name. Do not change as much as possible.
    Type: String
    Default: xxx-handson
    AllowedValues: 
      - xxx-handson
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Common
        Parameters: 
          - YYYYMMDD
          - HandsonName

Resources:
# SSM
  SSMYYYYMMDD:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${HandsonName}/YYYYMMDD
      Value: !Ref YYYYMMDD
      Type: String
  SSMHandsonName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${HandsonName}/HandsonName
      Value: !Ref HandsonName
      Type: String
